### ISSUE TITLE
Unable to build.

### ISSUE THREAD

**Issue by chibill** [nailed/mcp#6]
Compile Scala stops gradle build with an error. This is on windows.

**Comment by wgaylord** [comment]
@jk-5

**Comment by MMeent** [comment]
maybe you could send us an crash report/send us the log your build fails with? that would help debugging quite a lot

**Comment by wgaylord** [comment]
Just tell it to build. Its just a error in your code that it won't compile.... I will when I get home give you what it out puts on my end.

**Comment by jeffreykog** [comment]
Please give some logs and tell me what you are trying to do. For both @MMeent and me, it works without problems

**Comment by wgaylord** [comment]
Well I am getting it now. I am just trying to actually build the gradle plugin to use it as your maven repo is down. 

I will post the log right now.

**Comment by wgaylord** [comment]
Here is the output when I run gradle build --stacktrace on this repo to actually get the plugin.

http://pastebin.com/XAX1J527

**Comment by jeffreykog** [comment]
My maven repo (maven.jk-5.nl) is not down. It has had a 100% uptime for the last 30 days. Go to that site in your browser if you want to know which versions are available

**Comment by wgaylord** [comment]
It was not displaying anything but a black page till not.... So I guess this can be closed.

**Comment by jeffreykog** [comment]
Okay. If you need further help feel free to open another issue and i'll have a look.

**Comment by wgaylord** [comment]
Okay. Just not sure why it won't compile. (I think it has to do with me having java 8 JDK installed.)
