### ISSUE TITLE
How do you actually use this?

### ISSUE THREAD

**Issue by wgaylord** [nailed/mcp#7]
When ever I try using this. I get an error.

My build.gradle

buildscript {
    repositories {
        mavenCentral()
        maven {
            //Because SpecialSource 1.7 is still beta
            name = "sonatype"
            url = "https://oss.sonatype.org/content/repositories/snapshots/"
        }
        maven {
            name = "jk_5"
            url = "http://maven.jk-5.nl/"
        }
        maven {
            //MinecraftForge repo for Srg2Source
            name = "forge"
            url = "http://files.minecraftforge.net/maven"
        }
    }
    dependencies {
        classpath "jk_5.nailed.mcp:mcp:1.3.4"
    }
}

apply plugin: "nailed-mcp"

nailedMCP {
    minecraftVersion = "1.8"
}

And it out puts.
http://pastebin.com/WU6Qu4nG

**Comment by jeffreykog** [comment]
If you don't know how to use it, it's not for you

The point is, this gradle plugin was specially designed to be used with https://github.com/nailed/nailed with special code and magic made for that project.
It looks like you are trying to access unmodified minecraft code in a forgegradle way. For that, nailed-mcp is not what you are looking for. See https://github.com/Minecrell/VanillaGradle. I think that's what you want

**Comment by wgaylord** [comment]
I am trying to just use it in general... (I can't even get the tasks....)

**Comment by jeffreykog** [comment]
That is because you are missing some obvious steps. The error log tells you that a configuration file is missing. If you really want to use it you can have a look at nailed to see how it is used

**Comment by wgaylord** [comment]
Even with the a copy of the config folder from Nailed it gives the same error. Just trying to run gradle tasks

**Comment by jeffreykog** [comment]
If you read the error log you will know what went wrong. If you want me to have a look i should at least have access to that new error log
